lib/audited/auditor.rb, spec/audited/adapters/active_record/auditor_spec.rb, spec/audited_spec_helpers.rb
If a record is new and destroy is called on it, an audit for the destroy should not be created.  It causes an ActiveRecord exception:
```
ActiveRecord::RecordNotSaved: You cannot call create unless the parent is saved
```
This is a continuation of this pull request:  https://github.com/collectiveidea/audited/pull/79.  This version includes a (previously) failing spec.
=> Fix: Destroy on unsaved object should not audit

lib/audited/auditor.rb
AuditedClassMethods#without_auditing would not enable auditing on exception
using ensure block will enable back even when exception is raised inside the block
=> ensure enable back auditing on exception

lib/audited/auditor.rb, spec/audited/adapters/active_record/auditor_spec.rb, spec/audited/adapters/mongo_mapper/auditor_spec.rb
Without using `ensure`, `enable_auditing` will not get called when a
block passed to `.without_auditing` raises an exception.
=> Ensure `.without_auditing` reset auditing status

lib/audited/auditor.rb
Currently, line 55 on auditor.rb will fail if the table doesn't exist yet. Added a check if the table exists, if not, return from the method.
This case should only appear when setting up a new database (using a rake task) so we don't need the audit anyway.
=> Skip execution of audited if the table doesn't exist

lib/audited/adapters/active_record/audit.rb, lib/audited/auditor.rb, spec/audited/adapters/active_record/auditor_spec.rb
Seems to cause more problems than it solves. Easy to re-add for those people who want it.
=> Kill default scope

lib/audited/sweeper.rb
ActiveRecord callbacks fails for mongo mapper
=> sweeper need not run observer for mongomapper

spec/audited/audit_spec.rb
Small change, getting used to the codebase.
Here's the full rspec warning:
WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Actual error raised was #<StandardError: StandardError>. Instead consider providing a specific error class or message. This message can be supressed by setting: `RSpec::Expectations.configuration.warn_about_potential_false_positives = false`. Called from /Users/bronson/audited/spec/audited/audit_spec.rb:191:in `block (3 levels) in <top (required)>'.
=> fix 'raise_error without specific error' warning

README.md
I assumed these didn't exist and found them looking into what would be
needed to implement them!
There's probably a safety feature needed that raises if the first audit isn't a `create` type - otherwise you get bogus results (the newest version of the record, except for updates that have happened.) This scenario happens if you retrofit audited on to a class that has existing records.
I used the following migration which appears to work(?), would be nice if there was an official way of doing this (unless there is and I just missed it?).
```ruby
#
Record.find_each do |record|
if record.audits.any?
warn "Invalid state, record #{record.id} already has audits!"
next
end
record.send(:audit_create)
record.audits[0].update_attributes!(created_at: record.created_at)
end
```
=> Mention revision features in README.

lib/audited/auditor.rb
We can put the calls that trigger a database connection in a proc and only call it when first needed.
=> Do not connect to db until needed fix #239

lib/audited/rspec_matchers.rb
Similar to pull #185, this pull should eliminate the deprecation
warnings RSpec emits when using the audited RSpec matchers. Aliasing
the methods should leave it compatible with earlier versions of RSpec
as well.
=> Alias RSpec matcher methods for RSpec 3

.travis.yml, README.md
2.0 is EOL so we aren't going to explicitly test it anymore.
I suspect some people are still using 2.0, but since it is now unsupported I don't see a reason to explicitly support it going forward.
=> Remove Ruby 2.0 from Travis builds

README.md
If you follow instructions in the README, you'll end up with:
```
Bundler could not find compatible versions for gem "activemodel":
.....
audited was resolved to 4.2.0, which depends on
rails-observers (~> 0.1.2) was resolved to 0.1.2, which depends on
activemodel (~> 4.0)
....
```
This appears to be because rails-observers doesn't resolve to 0.1.3.alpha (presumably because it is alpha?).
=> Fixed README to avoid conflicts in rails 5.

lib/audited/auditor.rb, spec/audited/adapters/active_record/auditor_spec.rb
For compatibility with, e.g., sidekiq.
Otherwise, one thread disables audits other threads that should be auditing don't, until the first thread completes.
=> Make temporary disabling of auditing threadsafe

lib/audited/auditor.rb, spec/audited/auditor_spec.rb, spec/support/active_record/models.rb, spec/support/active_record/schema.rb
The store used for setting and checking auditing_enabled uses
`name.tableize`, which causes STI models to check the incorrect key - if
auditing is disabled on the parent, children should also not be audited.
=> Correct auditing_enabled for STI models

lib/audited/auditor.rb, spec/support/active_record/models.rb
Prior to this change, users would have to declare publicly scoped
callback handlers.
=> Allow private / protected callback declarations

lib/audited/auditor.rb
It's idiomatic to normalise scalar arguments and I noticed this is the
case for the `except` option so I modified the handling of the `on`
option to suit. This means we can:
```ruby
class SomethingAudited < ActiveRecord::Base
audit on: :create
end
```
A small change but it adds some consistency and is less 'surprising'
perhaps.
=> Normalise singular arguments for `on` option

lib/audited/auditor.rb, spec/audited/auditor_spec.rb, spec/support/active_record/models.rb
Currently it's possible to add non-column attribute and it will be audited even though we have `only` options specified.
The problem is that we rely on `ActiveModel::Dirty#changed_attributes` which records non-column attributes but we excludes column attributes only.
This PR adds a test case and working solution.
=> Fix auditing instance attributes if "only" option specified

lib/audited/auditor.rb, spec/support/active_record/models.rb
Allow to pass both singular value and array to `:only` option
```ruby
class SomethingAudited < ActiveRecord::Base
audit only: :password
end
```
Similar to https://github.com/collectiveidea/audited/commit/f62b770b23dd709a1728f9ff00d1d399d73f7fa0
=> Allow to pass both singular value and array to `:only` option

.travis.yml, Appraisals, README.md, audited.gemspec, gemfiles/rails40.gemfile, gemfiles/rails41.gemfile, gemfiles/rails42.gemfile, gemfiles/rails50.gemfile, lib/audited.rb, lib/audited/audit.rb, lib/audited/auditor.rb, lib/audited/rspec_matchers.rb, lib/audited/sweeper.rb, lib/audited/version.rb, spec/audited/audit_spec.rb, spec/audited/auditor_spec.rb, spec/audited/sweeper_spec.rb, spec/rails_app/config/routes.rb, test/install_generator_test.rb, test/upgrade_generator_test.rb
Prepping for a new version (4.3.0) since Rails 5 is final. 
Mostly testing and README changes.
Still need:
=> New release for Rails 5

lib/audited/audit.rb
With Rails Conditional GET support (304 caching), the `stale?` and `fresh_when` methods rely on `collection_cache_key`, which by default utilize the `updated_at` column.  Because the audits table doesn't include an `updated_at` column, this throws an SQL error.
This change simply changed the default and relies on `super`.
=> Set created_at as collection cache key

Appraisals, README.md, audited.gemspec, gemfiles/rails50.gemfile, lib/audited.rb, lib/audited/audit.rb, lib/audited/sweeper.rb, spec/audited/audit_spec.rb, spec/audited/sweeper_spec.rb
The `Audited::Sweeper` class made limited use of the cache sweeping
functionality provided by rails-observer, mostly using it as a way to
implement `Audit#before_create` on the same class that was attached
around controller actions.
Since there is no released version of rails-observer that's compatible
with Rails 5.0 (and not in the foreseeable future without considerable
refactoring), the population of IPs, users and request UUIDs is replaced
by thread-local storage and the existing `Audit#before_create` methods.
This is a net code reduction and somewhat simplifies the "sweeper" by
removing the assumptions about how rails-observer works.
=> Remove rails-observers dependency

.travis.yml, lib/audited/audit.rb, lib/generators/audited/install_generator.rb, lib/generators/audited/templates/install.rb, spec/audited/audit_spec.rb, spec/audited/auditor_spec.rb, spec/support/active_record/postgres/1_change_audited_changes_type_to_json.rb, spec/support/active_record/postgres/2_change_audited_changes_type_to_jsonb.rb, test/install_generator_test.rb
- update migration
- set postgres travis version to 9.4 to allow `jsonb`
=> `json` and `jsonb` as possible `audited_changes` column type, fix #216

README.md, lib/audited.rb, lib/audited/audit.rb, lib/audited/auditor.rb, lib/audited/rspec_matchers.rb, spec/audited/audit_spec.rb
Classes that inherit from `Audited::Audit` can be used instead of the
default by assigning `Audited.audit_class` in an initializer.
Resolves #314
=> Allow custom Audit classes

CHANGELOG.md, audited.gemspec, lib/audited/version.rb
Sorry @danielmorrison, a daft error I only noticed when viewing the published gem at rubygems.org.
=> Fix AR/Rails gemspec dependencies to permit 5.1

README.md, lib/generators/audited/install_generator.rb, lib/generators/audited/templates/install.rb, test/install_generator_test.rb
We use `uuid` as our primary key type on `users`, so we needed to tweak the install migration and are submitting back a generator option here.
If this is acceptable, I'm happy to add usage instructions to README.
=> Support UUID primary keys for User

lib/audited/audit.rb, lib/audited/sweeper.rb, spec/audited/sweeper_spec.rb
Restores behaviour prior to 87d402a where the sweeper would call the
controller's current_user method from the audited model callback.
Since 87d402a, the current_user method was called from an around action
callback registered on the base controller which was being called prior
to other callbacks that were authenticating the user. This caused
problems in apps where the user hadn't yet been set (so audit users were
nil), or CSRF issues because current_user was called prior to session
changes.
Fixes #336
=> Call controller's current_user method during audited model creation

audited.gemspec, lib/audited/auditor.rb, spec/audited/auditor_spec.rb, spec/audited_spec_helpers.rb, spec/support/active_record/schema.rb
Right now, even though the README file mentions symbol keys in `non_audited_columns`, they don't get filtered out as expected. To get `non_audited_columns` working as expected you have to pass the attribute names as strings.
This PR allows passing symbol keys.
=> Allowing using symbol keys in `non_audited_columns`

lib/audited/rspec_matchers.rb
Currently, the audited RSpec matchers throw an error:
`undefined local variable or method 'expect' for <Audited::RspecMatchers::AuditMatcher:0x007f8627d6ae48>`
when you use `.only` or `.except`.
The issue was a typo where it was referring to a non-existent variable `expect` instead of `except`.
Response to: https://github.com/collectiveidea/audited/issues/359
=> Fix typo in Audited RSpec Matchers

lib/audited/auditor.rb
No need to get the entire columns, we only need their names. Also cache
them instead of calculating again on every call.
=> Simplify audited_columns

lib/generators/audited/templates/install.rb, lib/generators/audited/templates/revert_polymorphic_indexes_order.rb, lib/generators/audited/upgrade_generator.rb
Current auditable & associated polymorphic indexes are using suboptimal columns order. PR for fixing order according to current Rails behavior in context of index structure for polymorphic association (https://github.com/rails/rails/commit/9cdd0a1fdf8308985231242d378e3a1c29c4ab00)
=> Columns order adjustment for polymorphic indexes

lib/audited/audit.rb, spec/audited/audit_spec.rb
I decided to create this PR as in our implementation of audited we needed to undo certain changes.
- Destroy models that were created
- Create models that were destroyed
- Change back attributes that were updated
=> Add support for undoing changes

.travis.yml, README.md
Updating travis config to cover latest ruby versions
=> update travis config to latest rubies

lib/audited/auditor.rb
=> Remove duplicated method

lib/audited/auditor.rb
`changes` (or `changes_to_save` in Rails>5.1) already gives us all the
changes in the format we need for saving the audit, no need to build
the hash again by ourselves.
=> Simplify audited_changes

CHANGELOG.md, lib/audited/auditor.rb, spec/audited/auditor_spec.rb, spec/support/active_record/models.rb
Normalizing options passed on audited initialization simplifies code in
further steps. Also cleaned up the code a bit.
=> Normalize options on initialization and minor cleanup

lib/audited/auditor.rb, spec/audited/auditor_spec.rb
* Previously, when a `record.revision(version)` was called
with a version number that was greater than the total
number of revisions, it would return the last revision
in the list. This changes it to return nil.
This addresses this issue raised here > https://github.com/collectiveidea/audited/issues/321.
=> Return nil on invalid revision number

README.md, spec/support/active_record/models.rb
As pointed out in issue #223, `allow_mass_assigment` has been removed and no longer has any effect. This updates the docs to no longer talk about it as it causes confusion to users of the gem.
=> Remove references to no-longer-supported allow_mass_assigment

CHANGELOG.md, lib/audited/auditor.rb
Follow up of https://github.com/collectiveidea/audited/pull/402.
Also replaced `.empty?` with `.exists?`, because for older rails'es (at least for 4.0.0) `.empty?` is implemented through `COUNT`, instead of through `SELECT 1` like in new versions.
=> Optimize reconstructing attributes in #revisions

gemfiles/rails52.gemfile, spec/audited/auditor_spec.rb, spec/audited_spec_helpers.rb
Rails 5.2.rc1 [introduced](https://github.com/rails/rails/pull/31727) some breaking changes for `ActiveRecord::Migrator`, so this PR fixes tests according to new changes.
=> Fix migrations in tests for rails 5.2

CHANGELOG.md, lib/audited/auditor.rb
This allows access to the audited object's relations from inside audits
without reloading it from the database. This is useful, for example, if
you want to check has_many relations which are deleted from the database
before the audit callback is executed.
=> Add inverse_of to audit relation

README.md
As @tbrisker pointed out in #415, I forgot to update the supported versions in the README.
=> Update Ruby versions in README

CHANGELOG.md, README.md, lib/audited.rb, lib/audited/auditor.rb, spec/audited/auditor_spec.rb
For minitest, for example:
Add to `test/test_helper.rb`:
```ruby
Audited.disable_auditing
```
And use:
```ruby
class UserTest < Minitest::Test
def setup
Audited.enable_auditing
end
def teardown
Audited.disable_auditing
end
def test_auditing
user = User.create!(name: "Dima", username: "dima")
assert_equal 0, user.audits.count 
end
end
```
Fixes #410
=> Add ability to globally disable auditing

CHANGELOG.md, lib/audited/auditor.rb
auditing_enabled was especially dangerous since it sets on the instance and modifies the global state
@tbrisker broken out from https://github.com/collectiveidea/audited/pull/356
=> remove unused/untested methods

CHANGELOG.md, lib/audited/audit.rb, lib/generators/audited/templates/add_version_to_auditable_index.rb, lib/generators/audited/templates/install.rb, lib/generators/audited/upgrade_generator.rb, test/db/version_6.rb, test/upgrade_generator_test.rb
This will optimize:
- two scopes from https://github.com/collectiveidea/audited/blob/c48893a680f23d27f7e255dfec2af91e7a00e350/lib/audited/audit.rb#L55-L56
as they always will be used with `auditable_id` and `auditable_type` (like in `user.audits.from_version(100)`), so new index will be used to speed this up;
- and here https://github.com/collectiveidea/audited/blob/c48893a680f23d27f7e255dfec2af91e7a00e350/lib/audited/audit.rb#L174 Notice also, that now no auditable object will be loaded in this line
Probably, this index should be a `UNIQUE` index, but there are possible race conditions, at least at previously mentioned line.
**Simple data for testing**:
```sql
INSERT
INTO audits (auditable_id, auditable_type, version)
SELECT i % 1000 + 1, 'User', random() * 1000
FROM generate_series(1, …
```
=> Add version to auditable_index

CHANGELOG.md, README.md, lib/audited/auditor.rb, spec/audited/auditor_spec.rb, spec/support/active_record/models.rb
=> Add `all_audits` method to auditable models

.travis.yml, README.md, audited.gemspec
drop all EOL ruby versions ... enable us to use frozen strings magic comments and newer syntax
@tbrisker
=> bump minimum ruby version

Appraisals, README.md, audited.gemspec, gemfiles/rails52.gemfile
- Fixes #440
- Bumped Rails version support on audited.gemspec
- Bumped Rails version support on gemfiles/rails52.gemfile
- Bumped Rails version support on Appraisals
- Added Rails 5.2 support to README
=> Add support for the final release of Rails 5.2

Appraisals, CHANGELOG.md, README.md, audited.gemspec, gemfiles/rails52.gemfile, lib/audited/version.rb
@danielmorrison - This backports permitting rails 5.2 on audited 4.7 stable branch, can you tag and release 4.7.1 please? (was requested in https://github.com/collectiveidea/audited/pull/441#issuecomment-380168068) 
The other changes in master branch will only be released in 5.0 version since they contain breaking changes.
=> Backport 5.2 support to 4.7 stable

CHANGELOG.md
I noticed the 4.7.1 changes were missing from the Changelog.md on master. This PR adds them back.
=> include 4.7.1 changelog updates [ci skip]

lib/audited/auditor.rb, spec/audited/auditor_spec.rb
Adding `true`as a second parameter to include private methods on conditional verification.
=> allow private methods on audited condition

CHANGELOG.md, lib/audited/auditor.rb, spec/audited/auditor_spec.rb, spec/support/active_record/models.rb, spec/support/active_record/schema.rb
```ruby
enum status: { new_status: "New", active: "In progress", complete: "Complete" }
```
Currently, when record is saved or destroyed, their audits contain enum values ("New", "In progress" or "Complete"). So I fixed "update" audits to store enum values as well for consistency. Also storing enum values (but not keys) allows to easily change enum key namings in future without changing existing audits. 
Fixes #202 
Fixes #214 
Fixes #412
=> Ensure enum changes are stored consistently

README.md, lib/audited/auditor.rb, spec/audited/auditor_spec.rb, spec/support/active_record/models.rb
Added on f2de4e606e97ec4c750dc9336d54cdffb88b7ab8
Currently there is a possibility to update an audit if only audit comment is present:
`assert_difference('post.audits.count', 1) { post.update_attributes(audit_comment: 'Only comment') }`
In my opinion, updating an audit with only comment given is purposeless, as in fact there are no changes at all
=> Add `update_with_only_comment` option

.travis.yml, Appraisals, CHANGELOG.md, README.md, audited.gemspec, gemfiles/rails42.gemfile, gemfiles/rails50.gemfile, gemfiles/rails52.gemfile, gemfiles/rails60.gemfile, lib/audited/audit.rb, spec/audited/auditor_spec.rb, spec/audited/sweeper_spec.rb, spec/rails_app/app/controllers/application_controller.rb, spec/rails_app/config/database.yml, spec/support/active_record/schema.rb
Includes Ruby 2.6 in the test matrix, fixes a deprecation and a couple of small issues that prevented tests running correctly on Rails 6.0.
Fixes #488
=> Support and test Rails 6.0

.travis.yml
See https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration for more details
=> Travis: Drop unused directive sudo: false

README.md
I was surprised there was no 2.6.x version tested, but it is actually tested, just not documented.
=> Document 2.6.3 as tested Ruby versions

README.md
MySQL 5.7 supports `json` column type and rails 5 have support for that similarly to postgres.
Mention this in README along with what happens by default.
=> Add info about mysql 5.7+ json type to readme

CHANGELOG.md, README.md, lib/audited/auditor.rb, spec/audited/auditor_spec.rb
Some models I only want auditing in certain conditions, this allows me to disable it by default and turn it on only when needed.
=> Allow for Audting to be enabled temporarily

README.md
For some reason, on my first read of this README, I totally missed the fact that you could pass a string in anywhere you can pass an ActiveRecord model. Having an example like this would have saved me some silly mock-object-creation. Willing to change the copy or the specificity of the example, but I have a feeling this is a common use case.
=> Include an example of passing strings to `as_user`

lib/audited/audit.rb
Thank you for your work on this gem. Please advise on any way I can improve this PR.
This change optimizes `set_version_number` by automatically setting version to 1 on create, helping performance in particular in cases of bulk inserts.
=> Avoid extra query by setting version to 1 when action is create

lib/audited/auditor.rb, spec/audited/auditor_spec.rb, spec/support/active_record/models.rb, spec/support/active_record/schema.rb
* In order to record that changes occurred, without storing sensitive
values, pass the `redacted` option.
* Redacted values default to `'[REDACTED]'` but can be customized with
the `redaction_value` option.
```
class User
audited redacted: [:password, :ssn], redaction_value: SecureRandom.uuid
end
```
* A lot of this was based on the work done [here](https://github.com/collectiveidea/audited/pull/339).
* Resolves https://github.com/collectiveidea/audited/issues/475.
=> Adds redacted option

lib/audited/auditor.rb
The method_missing might interfere with other method_missing in the class, e.g. ActiveRecord::Delegation#method_missing
https://github.com/rails/rails/blob/master/activerecord/lib/active_record/relation/delegation.rb#L111
I originally considered just defining the version method, but that was in the original PR, and it was decided not to do it.
https://github.com/collectiveidea/audited/pull/443#discussion_r180718047
I think the best way forward is just to remove the deprecation warning and to do a major version bump.
=> Remove deprecation warning, remove method_missing

Appraisals, gemfiles/rails60.gemfile, lib/audited/audit.rb, spec/audited/audit_spec.rb
- Fixes the gem spec for Rails 6 so it does not pull in Rails 6.1 rc builds
- Fixes the build in Rails 6.1 by not mocking the frozen object.
This should unlock at least the following two PRs #554 and #555
=> Fix Rails 6 and Rails 6.1 Builds

spec/audited/audit_spec.rb
I'm currently in Singapore (whose timezone is UTC+8), and this test was constantly failing:
```
Failures:
1) Audited::Audit.collection_cache_key uses created at
Failure/Error: expect(Audited::Audit.collection_cache_key).to match(/-20180101\d+$/)
expected "audited/audits/query-1ae402d409ee3a828c0f94e5cd171ef7-1-20171231160000000000" to match /-20180101\d+$/
Diff:
@@ -1 +1 @@
-/-20180101\d+$/
+"audited/audits/query-1ae402d409ee3a828c0f94e5cd171ef7-1-20171231160000000000"
```
Without using `Time.zone.parse`, the `Time.parse` method will default to the local timezone, which would cause an error in this specific case (4PM UTC is 12AM SGT).
=> Fix flaky test which would fail in certain timezones

README.md
I don't know if the `Audited.store` is meant to be used like that, but I spent a couple of hours trying to accomplish that today, so I thought it would be good to document it for future users trying to do the same thing.
To elaborate a little bit further, I needed to set a specific user as the auditor of all the commands in a console session. I patched the rails console to add an authentication with devise when opened, so that command comes right after a successful user login in the console.
=> Improved custom audit user section in README

lib/audited.rb, spec/audited_spec.rb
GraphQL added a [fiber-based batch loading API](https://github.com/rmosolgo/graphql-ruby/pull/3264) in one of their recent releases. 
Currently, Audited uses Fiber local state instead of Thread local state and is missing information during an audit.
I've fixed this by adding specs and changing store to Thread.
=> Use Thread local variables instead of Fibers

spec/support/active_record/schema.rb
Rails 6.1 introduced a change of ActiveRecord configurations.
Now we get a deprecation warning saying should use `configs_for`.
Here we check AR version and if it's newer than 6.1, use the latest API and `Tasks` for simpler setup.
=> Fix CI against Rails 6.1

lib/audited/audit.rb, spec/audited/sweeper_spec.rb, spec/rails_app/app/assets/config/manifest.js
**Description ***
Fixes a Rails 6 warning
> DEPRECATION WARNING: Class level methods will no longer inherit scoping from `create` in Rails 6.1. To continue using the scoped relation, pass it into the block directly. To instead access the full set of models, as Rails 6.1 will, use `Audit.default_scoped`.
*note:* It might possibly make sense to use `default_scoped` instead of `unscoped` but I feel that `unscoped` makes more sense since versioning should include records that might not be returned by `default_scoped`
=> Fix Rails 6.1 deprecations

lib/audited.rb, lib/audited/railtie.rb, lib/audited/sweeper.rb, spec/audited/sweeper_spec.rb
Depends on #530, because it won't pass specs without.
Thank you for this excellent gem, which we're using happily in production.
I encountered a conflict between `audited` and another gem which I believe is caused by the way audited hooks into Rails core classes. A minimal app displaying the behaviour is here: https://github.com/duncanjbrown/audited-bug. The behaviour is outlined on a rubyonrails-talk thread here: https://discuss.rubyonrails.org/t/understanding-a-conflict-between-two-activesupport-on-load-calls/74836.
Where an `on_load` reference is required to a non-ActiveSupport class (such as `ActionController::API`), wrapping the initialization code in a proper `railtie` prevents the weirdness I see in the above app. As far as I can tell this is the correct way to inject this code and …
=> Follow Rails autoloading conventions

lib/audited.rb, lib/audited/auditor.rb, spec/audited/auditor_spec.rb
Resolves https://github.com/collectiveidea/audited/issues/517 with a configuration flag to restore the previous behavior
=> Restore previous enum behavior with flag

lib/audited/auditor.rb, spec/audited/auditor_spec.rb
Here is another small fixes from the `stndardrb`. Without these changes, CI builds look like they are failing (e.g. https://github.com/collectiveidea/audited/pull/576, #577). Would be great if we could handle this as a separate PR so the CI will be ✅
=> standardrb fixes

lib/audited.rb
While PR collectiveidea/audited#532 worked to prevent `audited` from initializing certain rails components too early, an issue remains wherein the gem entrypoint, `lib/audited.rb`, immediately requires `lib/audited/audit.rb`.
Therein, `Audited::Audit` subclasses, `ActiveRecord::Base` and thereby causes it to load too early in the Rails boot process.
This simple change merely moves the `require` of `audited/audit` into the `AR` `on_load` block.
=> Resolve lingering issue from collectiveidea/audited#532

lib/audited/auditor.rb
Should effectively be the same query but easier to read and with the benefit of ActiveRecord's type casting and association reflection. Fixes issue dealing with mutiple id column types
=> Replace raw string where clause with query methods

lib/audited/auditor.rb, spec/audited/auditor_spec.rb
Ensures that auditing is re-enabled after `with_auditing` and `without_auditing` blocks.
Previously, if audits were disabled globally using `Audited.auditing_enabled = false` followed by use of a `with_auditing` or `without_auditing` block, then the class-level auditing is left disabled for the model on which `with_auditing` or `without_auditing` was called.
Resolves https://github.com/collectiveidea/audited/issues/534
=> Ensure audits are re-enabled after blocks

README.md, lib/audited/auditor.rb, spec/audited/auditor_spec.rb, spec/rails_app/config/environments/test.rb, spec/support/active_record/models.rb
Rails 7 introduces built-in attributes encryption: https://edgeguides.rubyonrails.org/active_record_encryption.html
Those are configured with `encrypts` keyword, eg: `encrypts :password`
Because these attributes are considered sensitive, we shouldn't write plain unencrypted values to our audits table by default.
=> Filter encrypted attributes automatically

lib/audited/auditor.rb
When combining audits the oldest remaining audit is updated and the audits over max_audit count are deleted.
This can result in a deadlock if if the same record is updated at the same time. However by virtue of being at the same time
the same end is being selected and the same verion number is used for the delete. This means the same update and same delete
are being performed for both audit combinations so this error can just be ignored.
=> Deadlocks from concurrent audit combinations

README.md
When I first implemented the associated feature, I assumed the `has_associated_audits` enabled auditing of the parent model AND connected the child audits. When I tested the `company.own_and_associated_audits` I got an `undefined method 'own_and_associated_audits'`. It took me a while to guess that I needed to also added audited to the parent model. 
I think adding the `audited` call to the parent will make the docs more explicit and devs will immediately realize that `has_associated_audits` is a extra/separate call.
=> Add audited method to parent in docs

.github/workflows/ci.yml
See their own spelling on:
https://www.postgresql.org/about/
=> Fix typo: PostgresSQL -> PostgreSQL

.github/workflows/ci.yml, README.md
Released 25 Dec 2022:
https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/
=> Add testing and document support for Ruby 3.2

.github/workflows/ci.yml
To all for an improved contributing experience, run GitHub actions on all branches.
When preparing a PR, I like to verify that all CI will be green on my personal fork. However, the existing GitHub actions configuration made it so this would not happen.
Now, contributors can run actions on their fork before opening a PR.
=> Run GitHub actions on all branches

lib/audited/audit.rb
so that audited gem can be used with non Rails projects, such as we do with Padrino
implements suggestions from https://github.com/collectiveidea/audited/issues/561
=> Replace Rails version check with ActiveRecord version check 

lib/audited/auditor.rb, spec/audited/auditor_spec.rb, spec/spec_helper.rb, spec/support/active_record/models.rb
Touch is a form of `update` which generally doesn't call callbacks.  It does, however, invoke an `after_touch` callback that can be leveraged to store away audit information.  This can be informative with fields such as `locked_at` housing a timestamp for when a user account is locked and `nil` when the user's account is unlocked.  Having historical information about when a user was locked/unlocked and auditing comments around the why, is handy.
=> Audit touch calls

spec/audited/auditor_spec.rb
A tiny update to a spec related to #657 to ensure the spec is testing the touched audit specifically.
=> Ensure testing of touched audit

lib/audited/auditor.rb, spec/audited/auditor_spec.rb, spec/support/active_record/models.rb
When introducing the touch audit, we overlooked touch on association (`belongs_to :model, touch: true`) and this PR resolves that.  This comes up when a model has an association setup w/ a touch, which could possibly be behind the scenes like when it comes to ActiveStorage objects.
E.g. W/ a basic model setup
```ruby
module Company < ApplicationRecord
has_many :employees
end
module Employee < ApplicationRecord
belongs_to :company, touch: true
end
```
If a company is created w/ an employee included...
```ruby
company = Company.create!(name: "Company A", employees_attributes: [{ name: "Employee 1", hired_at: Time.zone.current }])
```
Before this update we would end up with a "create" and an "update" audit for the company where the "update" audit is essentially the same data as the "create" …
=> Don't double audit on touch for create / update actions

lib/audited/auditor.rb, spec/audited/auditor_spec.rb, spec/support/active_record/models.rb
If records are looking to audit for touch, but have yet to be audited, or are specifically auditing _just_ touch events, ensure we're not failing due to a bad previous audit check.
=> Touch Audit - Ensure previous auditing

audited.gemspec, lib/audited.rb, spec/audited_spec.rb
Related to: https://github.com/collectiveidea/audited/issues/601 and inspired by: https://github.com/paper-trail-gem/paper_trail/commit/e28d29ef0f58cded1537df57551b73ac5b081b36
=> Use RequestStore instead of Thread.current for thread-safe requests.

lib/audited/auditor.rb
As pointed out by @akostadinov in the last PR, [here](https://github.com/collectiveidea/audited/pull/662#discussion_r1124546706) this PR cleans up the touch looking at previous audit logic a bit.
=> Touch Audit - a little cleanup

lib/audited.rb
A follow-up change to https://github.com/collectiveidea/audited/pull/655. This is required to make audited gem usable by non-Rails projects.
=> Conditional require railtie to support using audited gem in non-Rails projects

lib/audited/audit.rb, lib/generators/audited/migration.rb, spec/rails_app/config/application.rb, spec/support/active_record/models.rb
Ensure Rails versions are properly checked, instead of relying on `String` comparisons.
Example of why this is an issue
```ruby
[8] pry(main)> Rails.version > "10.2.3"
=> true
[9] pry(main)> Gem::Version.new(Rails.version) >= Gem::Version.new("10.2.3")
=> false
```
This example was taken from [this comment](https://github.com/collectiveidea/audited/pull/686#discussion_r1353239732) on a recent PR.
This change leverages the already existing function `Rails.gem_version`. This has been part of the Rails codebase for 10+ years, making it compatible with all supported Rails versions.
=> Robustify Rails version checks

README.md, lib/audited.rb, lib/audited/auditor.rb, spec/audited/auditor_spec.rb
Related comment/discussion: https://github.com/collectiveidea/audited/pull/662#issuecomment-1637265004
With the addition of [touch auditing](https://github.com/collectiveidea/audited/pull/657), I thought maybe a configuration  could exclude certain callbacks unless the callback action was specified on the model.
```Ruby
Audited.ignored_default_callbacks = [:touch]
class User < ActiveRecord::Base
audited
end
class Company < ActiveRecord::Base
audited on: [:create, :touch]
end
```
=> Ignore callbacks if not specifed on the model

lib/audited/auditor.rb, spec/audited/auditor_spec.rb, spec/support/active_record/models.rb
=> fix: normalize enum changes before filtering duplicate audits on touch

.github/workflows/ci.yml, audited.gemspec, lib/audited.rb, spec/audited_spec.rb, spec/spec_helper.rb
Based on the work done here: https://github.com/collectiveidea/audited/pull/673 by @the-spectator
=> Replace RequestStore with ActiveSupport::CurrentAttributes

lib/audited/auditor.rb
This commit allows max_audits value to be set dynamically (e.g., based on the level of subscription a user has).  It accepts a symbol or proc which are evaluated dynamically.
=> dynamic max_audits to be proc or symbol

audited.gemspec
Rails main is at 8.1 now, since we have test coverage for rails main branch already, it should be safe to allow rails 8.1 to install. Otherwise people using edge rails will install legacy 4.2.2 version, which doesn't work well.
=> Relax gemspec to allow Rails 8.1

lib/audited/auditor.rb, spec/audited/auditor_spec.rb, spec/support/active_record/models.rb
Allow `audited` to be called multiple times
When `audited` is called for the first time, setup audit normally
However if `audited` is called on a class that is already audited we update `audit_options` and log a warning message
an example of the warning message logged:
Fixes #731
=> allow calling audited multiple times
