- README.md
- audited.gemspec
- lib/audited.rb
- lib/audited/auditor.rb
- lib/audited/version.rb
Can we make dedicated 4.2 release for rails 4.2?
> Rails 4.2 support

- lib/audited/auditor.rb
Reverts collectiveidea/audited#149
> Revert "Skip execution of audited if the table doesn't exist"

- .travis.yml
- Rakefile
- spec/audited/adapters/active_record/active_record_spec_helper.rb
- spec/rails_app/config/environments/test.rb
- spec/spec_helper.rb
- spec/support/active_record/schema.rb
Remove mongo remnants. Extract database setup into a new task.
> Cleanup Rakefile

- lib/audited/auditor.rb
> Do not eagerly connect to database

- README.md
I scratched my head a bit on this one. I could only find my answer here https://github.com/collectiveidea/audited/blob/cd7065ef6fb9640a3a4e204477dd38dc0d12e50c/lib/audited/adapters/active_record/audit.rb#L40
> Add a Custom Auditor mention to the README

- CHANGELOG
> Add 4.2.1 and 4.2.2 to changelog

- lib/audited/auditor.rb
- spec/audited/auditor_spec.rb
> Restore non_audited_columns= configuration setter

- CHANGELOG.md
- README.md
- lib/audited/version.rb
@danielmorrison would you mind cutting the release?
> Bump version and refresh changelog for 4.4.0

- lib/audited/auditor.rb
Fixes https://github.com/collectiveidea/audited/issues/371
> Use updated AR::Dirty API to find changed attributes

- Appraisals
- gemfiles/rails40.gemfile
- gemfiles/rails41.gemfile
- gemfiles/rails42.gemfile
- gemfiles/rails50.gemfile
- gemfiles/rails51.gemfile
The format of gemfiles was changed by `bundle exec appraisal install`.
> Use Rails 5.1.4 instead of Rails 5.1.0.rc1

- spec/spec_helper.rb
This allows running specs using rake.
> Require bundler in spec_helper

- CHANGELOG.md
- README.md
- lib/audited/version.rb
@danielmorrison can we release a new version please with all the recent changes? 
I don't mind tagging once this is in but I don't have permissions to push to rubygems.
> Prepare for 4.6.0 release

- .travis.yml
Updates the following versions:
2.2.8 -> 2.2.9
2.3.5 -> 2.3.6
2.4.2 -> 2.4.3
> Test against updated Ruby versions

- CHANGELOG.md
- README.md
- lib/audited/version.rb
@danielmorrison can we haz :shipit: please? :smile_cat:
> Prepare for 4.7.0 release

- lib/audited/audit.rb
So I'm heavily modifying audited and I realized this logic could be a little simpler (and maybe make less SQL requests if eager_loading happens?).
> Simplify the undo logic

- CHANGELOG.md
- lib/audited/audit.rb
- spec/audited/audit_spec.rb
related issue:
https://github.com/collectiveidea/audited/issues/449
> add nested auditing

- .rubocop.yml
- .travis.yml
- audited.gemspec
- lib/audited/audit.rb
- spec/audited/auditor_spec.rb
- spec/support/active_record/schema.rb
@tbrisker 
starter PR to later slowly add more things like frozen strings etc performance related things and maybe some styles if there is consensus
> basic rubocop checks and fixes

- spec/audited/auditor_spec.rb
- spec/rails_app/config/application.rb
- test/test_helper.rb
> fix tests on 2.5 and reduce noise for sqlite tests

- CHANGELOG.md
- lib/audited/audit.rb
- lib/audited/auditor.rb
- spec/audited/auditor_spec.rb
Just taking [this pull request](https://github.com/collectiveidea/audited/pull/307) the last few inches to finish it up since it had gone stale. 😄
> rename instance attribute version to audit_version (Part Deux)

- .travis.yml
> Build all stable branches on Travis CI

- CHANGELOG.md
- lib/audited/version.rb
Ping @danielmorrison - I backported all of the non-breaking changes from the master branch to a new 4.8 branch. Can we release 4.8.0 please?
Opening this PR also to make sure tests run on this branch.
> Prepare 4.8.0 release

- .travis.yml
- audited.gemspec
Couple of fixes to resolve the current build failures on Travis CI, affecting #327 and others.
> Fix Bundler installation on Travis

- CHANGELOG.md
- README.md
- lib/audited/version.rb
https://github.com/collectiveidea/audited/issues/506
> Bump version 4.9.0

- README.md
Added reference to initializer file name audited.rb
> Updated readme for initializer file name.

- README.md
Just adding the previous config flag I added to the README
> Document store_synthesized_enums flag

- .travis.yml
- audited.gemspec
- lib/audited/auditor.rb
- spec/audited/auditor_spec.rb
- spec/audited/sweeper_spec.rb
I'm basically re-sending #579. I know this includes all the commits from #574 but I just wanted to be a bit more helpful and give a ✅ so you can more easily merge the PR and keep the master branch green.
Let me know if there is anything I could do.
> Update travis.yml to reflect the current state of the Ruby/Rails versions

- lib/audited/audit.rb
- lib/audited/auditor.rb
- spec/audited/audit_spec.rb
- spec/audited/auditor_spec.rb
- spec/support/active_record/models.rb
- spec/support/active_record/schema.rb
This is a revised version of https://github.com/collectiveidea/audited/pull/448, which addresses https://github.com/collectiveidea/audited/issues/446 and https://github.com/collectiveidea/audited/issues/191.
The main differences are:
1. Based off of the latest commit on `master`
2. Uses `serialize :phone_numbers, Array` to replicate the issue
The rest is pretty much the same. Please let me know if there's anything you need.
cc @cfeckardt
> Fix array support

- lib/audited-rspec.rb
- lib/audited.rb
- lib/audited/audit.rb
- lib/audited/auditor.rb
- lib/audited/railtie.rb
- lib/audited/rspec_matchers.rb
- lib/audited/sweeper.rb
- lib/audited/version.rb
- lib/generators/audited/install_generator.rb
- lib/generators/audited/migration.rb
- lib/generators/audited/migration_helper.rb
- lib/generators/audited/templates/add_association_to_audits.rb
- lib/generators/audited/templates/add_comment_to_audits.rb
- lib/generators/audited/templates/add_remote_address_to_audits.rb
- lib/generators/audited/templates/add_request_uuid_to_audits.rb
- lib/generators/audited/templates/add_version_to_auditable_index.rb
- lib/generators/audited/templates/install.rb
- lib/generators/audited/templates/rename_association_to_associated.rb
- lib/generators/audited/templates/rename_changes_to_audited_changes.rb
- lib/generators/audited/templates/rename_parent_to_association.rb
- lib/generators/audited/templates/revert_polymorphic_indexes_order.rb
- lib/generators/audited/upgrade_generator.rb
I appreciated this from #460 so pulling it in here.
> Add frozen_string_literal: true to main files

- lib/audited/auditor.rb
details https://github.com/collectiveidea/audited/issues/583
> [#583] Disabled audited skips associated model loading

- README.md
> Update supported rubies.

- .github/workflows/ci.yml
- Appraisals
- README.md
- audited.gemspec
- gemfiles/rails50.gemfile
- gemfiles/rails51.gemfile
- gemfiles/rails52.gemfile
- lib/audited/audit.rb
- lib/audited/auditor.rb
- lib/generators/audited/migration.rb
- spec/audited/auditor_spec.rb
- spec/rails_app/config/application.rb
Getting tests fixed for me locally, and on GitHub.
> Test Fixes

- README.md
- lib/audited.rb
- lib/audited/audit.rb
- lib/audited/auditor.rb
- lib/audited/rspec_matchers.rb
- spec/audited/audit_spec.rb
> Use string class name and constantize

- lib/generators/audited/migration.rb
Close https://github.com/collectiveidea/audited/issues/623.
> Fix timestamped_migrations deprecation warning

- spec/audited/auditor_spec.rb
I noticed two bugs with `redacted` config option. This PR fixes them both.
Given following simple configuration:
```ruby
class User
audited redacted: :password
end
```
```
User.last.update(name: 'John')
User.last.audits.audited_changes
=> {"name"=>["Bob", "John"], "password"=>"[REDACTED]"}
```
In this example, `password` wasn't changed, but it appears in the `audited_changes`.
What is worse, `password` contains single value, while `update` actions are expected to have an array `[prev_value, new_value]`
```
User.create(name: 'John', password: '123')
User.last.audits.audited_changes
=> {"name"=>"John","password"=>"123"}
```
In this example, password is not replaced to `[REDACTED]` placeholder.
Same for `delete` action.
PS: I also refactored `redact_values` method a little bit, so it will be …
> Fix redacted attributes bug when no changes were made

- lib/audited/auditor.rb
- spec/audited/auditor_spec.rb
- spec/audited_spec_helpers.rb
- spec/support/active_record/models.rb
> Ignore readonly columns in audit
